dianna-ai/dianna

dianna/__init__.py
dianna/methods/lime.py
dianna/methods/rise.py
dianna/visualization/text.py
tests/test_common_usage.py
tests/test_lime.py
tests/test_rise.py
tests/test_text_visualization.py
tests/utils.py

fixes 'https://github.com/dianna-ai/dianna-exploration/issues/138'
Introduces a `labels` parameter for both rise and and lime. Both return an object of the same structure.

make rise and lime apis consistent

---

dianna/methods/rise.py

Ensure data fed to model has same dtype as input data in RISE

---

.github/workflows/build.yml
project_setup.md
setup.cfg

Remove python 3.6 from setup.cfg and build matrix

---

README.md
badges.md

optimizes the badges from our readme

remove complete badges section from readme (refs #52)

---

README.md

The link saying "more badges" after the badges is a bit ugly. This commit makes it a badge too.

add "more badges" badge

---

dianna/utils/misc.py

Now it only returns (keyword) args
Fixes #119

Fix that get_kwargs_applicable_to_function would also return locals

---

README.md

add JOSS style metadata header to README.md

---

dianna/visualization/text.py
setup.cfg
tutorials/README.md
tutorials/lime_text.ipynb

- Adds the movie reviews dataset
- Adds a LIME on text tutorial
- Fixes bug in highlight_text (it wouldn't show the html properly)

LIME on text tutorial

---

tutorials/README.md
tutorials/rise_text.ipynb

The results are not amazing, but it's working.
I think we might want to change something in how RISE masks sentences, but I'll open a separate issue for that.

Add RISE on text tutorial

---

dianna/methods/kernelshap.py

Add preprocess function option to kernelshap

---

README.md

Does it help to point to Ben's issue? If you have suggestions for a clearer text, that is also welcome. I don't dare to write it down in more details because I don't really know what has changed. You can also just press merge/approve if you agree with what I wrote.

update readme, refer to latest m1 issue

---

dashboard/callbacks.py

Always use labels keyword in dashboard, label (singular) does not exist

---

dianna/__init__.py
dianna/methods/kernelshap.py
tests/test_kernelshap.py

Make user input for method no longer case sensitive

---

README.md

We have found no solution within dianna for issue #376. There are some possible workarounds, which are now linked to from the README.

Add note about openmp error to installation instructions

---

setup.cfg

Pin prospector version to avoid pyroma install error

---

dashboard/callbacks.py
dashboard/layouts.py

Created:
- second text upload option
- Input parameters are the same for both strings
- Predictions are made and printed for each of the strings
- Relevances are plotted side by side for the different strings
Should work for one or two selected methods, and one (does not matter which one) ore two uploaded strings.

441 implement text side by side

---

dashboard/callbacks.py
dashboard/layouts.py

Reverts dianna-ai/dianna#452
Keep branch but delete merge from main to implement text side by side, because we decided that we will not implement multiple inputs, but focus on multiple-label explanations

Revert "441 implement text side by side"

---

dianna/methods/lime.py
dianna/utils/tokenizers.py
tests/test_text_visualization.py

Make input text lowercase before tokenizing

---

setup.cfg

Add notebook requirement

---

setup.cfg

[See issue 528](https://github.com/dianna-ai/dianna/issues/528)

Downgrade dash

---

README.md
docs/ROADMAP.md
tutorials/README.md

529 update readmes and roadmap

---

.github/workflows/build.yml
.github/workflows/documentation.yml
.github/workflows/fair-software.yml
.github/workflows/linting.yml
.github/workflows/markdown-link-check.yml
.github/workflows/notebooks.yml
.github/workflows/sonarcloud.yml

This PR adds a line to only run the CI on PRs that are ready for review. For more info see the issue.
Closes #519

Run CI only on PRs ready for review

---

CITATION.cff
README.md

This PR adds myself as an author to the citation.ciff
I also fixed a small issue with the doi to zenodo, which was not pointing to the latest version.

Add author to citation.cff and update readme

---

CITATION.cff

maybe there needs to be some orcid added if Willem has one?

add Willem as an author to the CITATION.cff

---

README.md

Add tabular example to getting start section in readme.
This PR closes #686 .

Add tabular example to getting start in readme

---

README.md
tutorials/README.md

Update READMEs.md with blog-posts

---

tutorials/explainers/RISE/rise_imagenet.ipynb
tutorials/explainers/RISE/rise_mnist.ipynb
tutorials/explainers/RISE/rise_text.ipynb
tutorials/explainers/RISE/rise_timeseries_frb.ipynb
tutorials/explainers/RISE/rise_timeseries_weather.ipynb

improved link to RISE paper- the conference publication, not the argxiv one

issue #724 Update RISE paper links in tutorials

---

tests/test_visualization.py

add more test for text visualization

---

dianna/dashboard/readme.md

added quotes around the dashboard installation command such that it will work directly for zsh terminals

fix dashboard installation requirements command
