- .github/workflows/sonarcloud.yml
- .gitignore
- dianna/methods/lime.py
- dianna/utils/__init__.py
- dianna/utils/misc.py
- pyproject.toml
- setup.cfg
This PR will allow users to pass along all possible keyword arguments to the explainer methods. It does this by adding `**kwargs` to the `explain_image/text` functions and passing them along appropriately (i.e. forwarding the proper keyword arguments to the proper call sites; some explanation methods need multiple calls and these calls may not support the same set of keyword arguments, so we need to filter the `**kwargs` dict for which a helper function was created in `utils`).
I propose to also remove a few existing keyword arguments that had the same defaults as those in the explainer libraries. These can now still be changed by the user by providing it through `**kwargs`, but we don't have to maintain the default values anymore.
Finally, I update documentation on our side a bit. We …
> Allow all method keyword arguments

- tests/test_rise.py
The tests now correctly generates heatmaps of shape (28, 28), instead of (1, 28)
> Fix shape of output in rise test; closes #62

- dianna/utils/onnx_runner.py
- tests/test_lime.py
- tests/test_onnx_runner.py
- tests/test_rise.py
Now that we keep track of the dtype of the data given by the user, we no longer 
need to do any conversion explicitly. 
This PR removes the explicit conversion to float32 in SimpleModelRunner, and adds explicit conversion
of the input data used in tests.
> Remove explicit dtype conversion in SimpleModelRunner

- dianna/methods/lime.py
- dianna/methods/rise.py
- dianna/utils/misc.py
- tests/test_common_usage.py
- tests/test_lime.py
- tests/test_rise.py
- tutorials/rise_mnist.ipynb
Because axis should really be singular here and it's leading to confusion.
> Rename axes_labels parameter to axis_labels

- .github/actions/install-python-and-package/action.yml
- .github/workflows/build.yml
- .github/workflows/linting.yml
- .github/workflows/notebooks.yml
- .github/workflows/release.yml
- .github/workflows/sonarcloud.yml
- setup.cfg
> Add testing of tutorial notebooks using nbmake

- .github/actions/install-python-and-package/action.yml
- setup.cfg
Currently the notebooks action in main is failing. One of the issues is that it misses the torchvision requirement. This PR fixes that issue. Other issues still remain after this PR, for instance, the missing ferrari.jpg (of which the license is unclear).
Feel free to merge if you approve. It's a tiny PR anyway.
> add notebooks extras_require for running notebooks

- .github/actions/install-python-and-package/action.yml
- .github/workflows/notebooks.yml
- .github/workflows/release.yml
This commit/PR:
1. Adds the option in the install action to specify which extras-require options to use (dev, notebooks, publish).
2. Uses the above to minimize the dependencies that have to be installed for each workflow.
3. Installs wheel in the first step of the dependencies installation. This allows pip to download wheels in the second step (installing dianna and dependencies), which reduces install time.
> optimize CI pip dependency installation

- .github/workflows/markdown-link-check.yml
- .github/workflows/markdown_link_check_cron.yml
Fixes #190 
- changes the old markdown link checker to only check links in changed files (but check the complete file then, not just diff)
- add new link checker that checks every thing monthly
> separate link checker

- .github/workflows/cffconvert.yml
- CITATION.cff
Hello!
We noticed that your CITATION.cff had a small issue and fixed it - possibly by just updating `cffversion` to 1.2.0.
In addition to the fix, this PR also updates cffconvert-github-action to 2.0.0.
In the new version, the cffconvert-github-action does not compare against Zenodo anymore, because Zenodo is using CITATION.cff directly now (see [this twitter post](https://twitter.com/zenodo_org/status/1420357001490706442)).
BTW it's perfectly fine if you don't feel like accepting this Pull Request for whatever reason -- we just thought it might be helpful is all.
We found your repository using a partially automated workflow; if you have any questions about that, feel free to create an issue over at https://github.com/cffbots/filtering/issues/
On behalf of the cffbots team,
@abelsiqueira …
> Add cffconvert.yml to validate CITATION.cff

- dianna/methods/rise.py
- tests/test_rise.py
The default mask string is "UNKWORDZ", which most likely isn't in any tokenizer's dictionary.
This is the same value as is used internally in LIME. The name of the parameter (`mask_string`) is also identical to LIME, the DIANNA API remains consistent with respect to this parameter.
> In RISE for text, mask tokens with a user-definable string instead of removing  them

- paper/paper.md
I removed Mathematics and Citations sections (I left References at the end as is done in the [recent paper example](https://joss.theoj.org/papers/10.21105/joss.03951)), and as it seems to be suggested in the [review criteria](https://joss.readthedocs.io/en/latest/review_criteria.html). I also inserted State of the field and Key Features sections. 
I left Figure section, also if I don't think is needed (see [recent paper example](https://joss.theoj.org/papers/10.21105/joss.03951))
> revisit joss skeleton

- .github/workflows/build.yml
- setup.cfg
> Run tests also on python 3.10

- dashboard/callbacks.py
- dashboard/utilities.py
When working on the tokenizers we changed how text visualization works, but didn't realize that the dashboard uses its own visualization function. This PR changes the dashboard visualization for text to work in the same way as in the main code
> Fix text visualization in dashboard

- dianna/utils/__init__.py
I think a user is not able to import the SimpleModelRunner at the moment. That must be a mistake. This commit exposes it to the user so they can reuse it.
I think this PR can be approved if any reviewer agrees on both questions below:
Do you agree that the class could not have been imported by a users before adding it to the __init__?
Do you agree that we want to make this part reusable?
> expose SimpleModelRunner to user

- paper/paper.md
I tried to improve the English of this section, as suggested in our JOSS paper review. Feel free to edit my changes / add others.
> Address reviewer suggestion about Used by

- dianna/utils/__init__.py
- dianna/utils/tokenizers.py
- setup.cfg
- tutorials/lime_text.ipynb
- tutorials/rise_text.ipynb
The previous release is broken if the user does not have torchtext installed, see #357.
This PR makes torchtext optional, by not always importing the tokenizer anymore. An informative error is raised when the user tries to import a tokenizer when torchtext is not available. A dianna[text] variant is added to allow the user to automatically install the required dependencies for text-based explanations.
> Remove torchtext dependency

- paper/paper.bib
Close #394.
This fixes one doi was incorrect and adds a couple of dois to references without a doi, as suggested by the JOSS bot.
> fix 1 doi and add 5 new dois (fix #394)

- dianna/methods/rise.py
- tests/test_rise.py
Fixes #380 
This bug and its fix takes some knowledge of how RISE works to review.
We have 3 behaviors to talk about: The old actual behavior (that we considered bugged) which is the code of the main branch, the old intended behavior, and the new behavior as proposed in this PR.
Note that the ultimate goal here is to pick the best p_keep. For this we calculate a score for every p_keep. 
We do this by masking instances with N random masks and make predictions for all. The result is a matrix of N by C (`number of classes`). We then calculate a score based on those and pick the p_keep with the highest score. This was the same for all 3 behaviors. The way the score was calculated was different.
The old intended behavior was as follows. For each of the classes we take the std over all N …
> change p_keep autotuning behavior (fixes #380)

- .prospector.yml
Each linting issue is listed twice in our CI, see e.g. https://github.com/dianna-ai/dianna/actions/runs/3524834941/jobs/5910769814
This PR fixes that by removing the build directory from prospector
> Ignore build directory when running prospector

- dianna/methods/kernelshap.py
- dianna/methods/lime.py
- dianna/methods/rise.py
- dianna/utils/__init__.py
- dianna/utils/misc.py
- tests/test_kernelshap.py
- tests/test_lime.py
- tests/test_rise.py
This PR is an attempt at making the axis_labels argument optional. The only required label left was the colour channels index. A new utils function is added that attempts to automatically determine the location of the channels axis. This does require a few assumptions:
- The channels axis has a size of either 3 (RGB) or 1 (greyscale)
- The channels axis is either the first or the last axis
When we can't find the channels axis, we raise an error and tell the user to use axis_labels.
Even if we do find it, we give a warning as we have no way of knowing for sure we correctly identified the channels axis.
I'm not sure always giving a warning is the best solution, other suggestions are more than welcome.
Note: I've also modified a few tests to make sure that for each method, there is at least …
> Make axis labels optional

- README.md
- docs/developer_info.rst
- setup.cfg
Fixes #381. Adds link to already existing but hard to find developer documentation. This contains the requested test documentation. Also updates the developer documentation with respect to the supported python versions.
> update test instructions

- dashboard/callbacks.py
- dianna/__init__.py
- dianna/methods/kernelshap.py
- dianna/methods/lime.py
- dianna/methods/rise.py
- tests/test_common_usage.py
- tests/test_kernelshap.py
- tests/test_lime.py
- tests/test_rise.py
- tutorials/demo.ipynb
- tutorials/kernelshap_geometric_shapes.ipynb
- tutorials/kernelshap_mnist.ipynb
- tutorials/lime_text.ipynb
I changed the signatures of all explain_image or explain_text definitions. I changed the label kwarg into a positional argument. No need for error checking because it is now automatically a TypeError to call any of those methods without a labels argument.
> make label a required argument (Fixes #131)

- setup.cfg
Version 1.8.4 should have fixed the issues previously mentioned in #423. See https://github.com/PyCQA/prospector/milestone/7?closed=1. Also relevant to the discussion in https://github.com/NLeSC/python-template/issues/327
> Unpin prospector

- dianna/methods/lime.py
- dianna/methods/rise.py
- dianna/utils/__init__.py
- dianna/visualization/__init__.py
- tests/test_common_usage.py
This solves all linter issues currently in main.
Most issues were solved by adding disabling comments. Wherever possible, I tried adapting the code instead to satisfy to linter rules. For instance, I did some refactoring to get the number of variables in scope down in `rise.py`.
> refactor rise and fix linter issues (refs 447)

- .github/actions/install-python-and-package/action.yml
- .github/workflows/build.yml
- .github/workflows/documentation.yml
- .github/workflows/fair-software.yml
- .github/workflows/linting.yml
- .github/workflows/markdown-link-check.yml
- .github/workflows/notebooks.yml
- .github/workflows/sonarcloud.yml
This PR caches the python environment. This will significantly reduce the time it will take to run the tests on github actions.
All steps should run roughly 2-3x faster now. I also made it so that the tests only run when the PR is ready for review. This helps save cpu cycles, and saving cpu cycles is good for the environment 🌱
Closes #475
> Cache python install in github actions

- dashboard/utilities.py
- dianna/methods/lime.py
- dianna/utils/tokenizers.py
- tests/test_lime.py
- tests/test_rise.py
- tests/test_text_visualization.py
- tests/utils.py
- tutorials/lime_text.ipynb
Fixes #437 . See that issue for more details on why the tokenizer was updated as a fix.
> Combine special characters into single token

- dashboard/app_data/labels_text.txt
- dashboard/callbacks.py
- dashboard/layouts.py
@laurasootes, I have added label file upload support to text as well. However, I am not able to test it due to WSL issues for text. Could you give it a go and let me know if it works fine?
> Added label file upload for text

- dashboard/callbacks.py
- pyproject.toml
- setup.cfg
This PR fixes the bug with label uploads where you cannot upload data outside the `FOLDER_ON_SERVER`. If labels are uploaded, look at the contents of the upload instead of the filename.
Closes #505
> Fix bug with label uploads

- dianna/utils/maskers.py
- tests/methods/test_maskers.py
Adds the ability to channel certain channels.
We can now 
- mask channels
- mask time steps
- make a combination of the above
We cannot do any completely random masking, which is fine I think, but could be discussed.
Note that I left some code duplication in the code for these different masking operations. I will change one of the 2 duplicates when I implement #546.
> 514 add channel masking

- tests/methods/test_lime_timeseries.py
This PR fixes the test which is broken due to the update of masking function for timeseries.
> Fix test of lime timeseries due to the update of masking function

- dianna/methods/lime_timeseries.py
- tests/methods/test_maskers.py
Fix #557.
Now it ensures the first instance is the original data, which satisfies the requirement from https://github.com/marcotcr/lime/blob/fd7eb2e6f760619c29fca0187c07b82157601b32/lime/lime_base.py#L148-L149
> 557 fix first instance issue for Lime timeseries

- .github/actions/install-python-and-package/action.yml
This PR skips the pip install step if the cache is restored. This saves a couple of minutes on every workflow run.
Saves:
- Windows: ~3 min
- Ubuntu: ~1 min
- Mac: ~3 min
> Avoid pip install in workflow if cache is hit

- tests/test_common_usage.py
Hey, I noticed that some of the tests are quite slow. I had a quick look and noticed the RISE image pipeline test can be made about 20 times faster by reducing the shape of the image:
Before:
`28.10s call     tests/test_common_usage.py::test_common_RISE_image_pipeline`
After:
`1.74s call     tests/test_common_usage.py::test_common_RISE_image_pipeline`
Since we are testing the pipeline only, the size of the image is irrelevant (it's filled with random data anyway). This takes the time needed to run the tests down from 0:01:59 to 0:01:31 on my setup.
> Improve test suite time by 25%

- dianna/methods/lime_timeseries.py
- dianna/methods/rise.py
- dianna/methods/rise_timeseries.py
- dianna/utils/maskers.py
- dianna/utils/predict.py
- tests/test_rise.py
In this PR we refactor `lime_timeseries`, `rise_timeseries` and `rise` to remove the duplicated prediction function in the code.
Also includes some minor refactoring changes.
Fixes #559.
> 559 address duplication predict function

- dianna/methods/kernelshap.py
- setup.cfg
see #613 it's just some very minor changes that should enhance compatibility and not impede functionality. Should be a quick review :)
> upped scikit-image and some naming changes

- README.md
Indicated there are tutorials for LIME and RISE for time-series. 
Updated tutorials table
Updated generic text Why DIANNA? Key points
Added time-series datasets
Solves issue #601
> Update README.md: added checks for LIME and RISE

- sonar-project.properties
`dashboard` is checked but since it is checked within subprocess it is not detected by sonarcloud coverage. This produces misleading results. So it is better to exclude the coverage check for dashboard from the report.
> Exclude coverage check for dashboard

- dianna/methods/rise.py
- dianna/utils/maskers.py
This is necessary for distance_explainer to be able to reuse it.
> refactor masker for RISEImage into free function

- .github/workflows/build.yml
- setup.cfg
This PR Fixes #623.
Why all the red crosses then?
- Does not fix #626 about the failing notebook tests.
- Also, linting is failing, but has been fixed in main already. Has nothing to do with this PR.
> add 3.11 support

- dianna/methods/kernelshap.py
- tests/test_kernelshap.py
This PR fixes #631. In some cases, kernelshap would over- or (worse) underallocate memory for the shapeley values leading to issues. This PR should fix this bug.
> fixed number of segments bug

- tests/test_lime.py
Some added tests for the 'tokenizer problem' that I encountered during the work as discussed with @stefsmeets in issue #633 . I have marked the tests with `mark.xfail` as suggested by [the guidelines here](https://docs.pytest.org/en/7.1.x/how-to/skipping.html ) (end of the page).
> added tests for the 'tokenizer problem'

- docs/IO_overview.md
closes #663 
relates #691
preview [here](https://github.com/dianna-ai/dianna/blob/add_overview/docs/IO_overview.md).
> Create overviews of inputs outputs

- dianna/utils/maskers.py
Gets rid of following warning:
/Users/runner/work/dianna/dianna/dianna/utils/maskers.py:106: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.) 
See in log: https://github.com/dianna-ai/dianna/actions/runs/8250917332/job/22566702492#step:4:622 line 571
> fix deprecation warning:

- setup.cfg
See https://github.com/dianna-ai/dianna/actions/runs/8250917332/job/22566702492#step:4:622 All builds [3.9,3.11]X[win, ubuntu,mac] pass except (mac,3.9). I think it's because it is using a new tf version 2.16 where the others are using 2.15. I also replicated this behavior locally but couldn't completely pinpoint the cause. It may also have something to do with the tensorflow-probability version.
I put another constraint on the tf version that will hopefully solve this for now.
> fix macos + 3.11 build

- README.md
Closes issue #720 
I've added a link to the FRB model and paper describing its generation.
I've not added a link to the dataset as it isn't public. We just use a single sample from the dataset in our tutorial.
> Add FRB model to main readme

- dianna/methods/lime_timeseries.py
- dianna/methods/rise_timeseries.py
- dianna/utils/maskers.py
- tests/methods/test_lime_timeseries.py
- tests/methods/test_maskers.py
Document the masking strategy by linking to the blog post I wrote about it.
Fixes #564 .
Note that the first commit are the actual planned changes. But I also changed a function name there to make it a bit more clear, which wasn't supposed to be part of this PR, but broke some imports. The second commit is fixing those imports.
> add a link to the time series masking blog post from docstrings

- tests/methods/test_rise_timeseries.py
Closes #690 
#690 describes the explainer not working with an onnx file for timeseries. After some testing, I found that the season prediction model requires float32 input, while numpy/python use float64 by default. This makes the season prediction model crash when using the onnx file. I don't think this should be considered a bug in dianna, rather the user should convert the data using the preprocess function. I added a test that does this.
> Add test for rise timeseries on onnx file

- dianna/dashboard/_movie_model.py
- tutorials/explainers/KernelSHAP/kernelshap_geometric_shapes.ipynb
- tutorials/explainers/KernelSHAP/kernelshap_mnist.ipynb
- tutorials/explainers/KernelSHAP/kernelshap_tabular_penguin.ipynb
- tutorials/explainers/KernelSHAP/kernelshap_tabular_weather.ipynb
- tutorials/explainers/LIME/lime_images.ipynb
- tutorials/explainers/LIME/lime_tabular_penguin.ipynb
- tutorials/explainers/LIME/lime_tabular_weather.ipynb
- tutorials/explainers/LIME/lime_text.ipynb
- tutorials/explainers/LIME/lime_timeseries_coffee.ipynb
- tutorials/explainers/LIME/lime_timeseries_weather.ipynb
- tutorials/explainers/RISE/rise_imagenet.ipynb
- tutorials/explainers/RISE/rise_mnist.ipynb
- tutorials/explainers/RISE/rise_text.ipynb
- tutorials/explainers/RISE/rise_timeseries_frb.ipynb
- tutorials/explainers/RISE/rise_timeseries_weather.ipynb
Use files from dianna installation folder in all tutorials.
This simplifies the colab setup as we no longer need to download data
files.
The relative paths throughout the tutorials were replaced by paths
starting from the dianna install dir, which should work on all
platforms.
The indentation in the colab setup was also fixed, this was 2 spaces
instead of 4 in many places.
Fixes #750
> Fix data file paths for Colab

- dianna/dashboard/_models_image.py
- dianna/dashboard/_shared.py
- dianna/methods/lime_timeseries.py
- setup.cfg
- tests/test_dashboard.py
This PR fixes #738 
Lime runs into an error because of a typo in the variable name -> rand_state instead of random_state.
Additionally lime timeseries does not have this variable, which also returns an error, since the random_state variable is used in all LIME methods. Although random_state is not used in lime timeseries, adding the variable to the class fixes the issue.
Edit:
Added tests for dashboard text, image, and timeseries for LIME and KernelSHAP to complete the dashboard tests. It turned out that the dashboard was actually not working for images with KernelSHAP. I made changes in dashboard/_models_image.py to do this, but I am not sure of the changes are 100% correct. Can someone please check @cwmeijer @loostrum maybe?
> 738 text lime in dashboard returns an error

- dianna/methods/lime_text.py
- tests/methods/test_lime_text.py
> sort lime text output based on index and not importance

- dianna/visualization/image.py
- dianna/visualization/tabular.py
Adds to the plot_image and plot_tabular functions an optional argument ax: plt.Axes. When given, this is the Axes that will be used to plot on and the internal plt.subplots call is skipped. This is useful for using these functions in custom multi-panel plots (we want to use this in a paper).
We actually only need this for the `plot_image` function, but I added it to `plot_tabular` as a bonus ;) The `plot_timeseries` function is too complicated, I don't have time to add it there right now, but the principle will be similar (except now the ax has to be passed through three layers of helper functions).
> enable passing of external Axes to plot on
